spring:
  datasource:
    url: jdbc:mysql://192.168.137.100:3306/spring_boot_flowable?characterEncoding=UTF-8
    username: root
    password: Root@123
flowable:
  #关闭定时任务JOB
  async-executor-activate: false